image: openjdk:11

stages:
  - build

build_app:
  stage: build
  script:
    - powershell -Command "& { Set-Item -Path Env:ANDROID_HOME -Value 'C:\Users\tomas\AppData\Local\Android\Sdk'; & .\gradlew assembleDebug }" 